# Site Settings
title: "Valerie Ang"
description: "M&T at Penn: Electrical Engineering & Finance"
url: "https://valeriekyang.github.io"
baseurl: "" # Leave this empty

# Remote Theme (Essential for Minimal Mistakes)
remote_theme: "mmistakes/minimal-mistakes"

# Author Profile
author:
  name: "Valerie Ang"
  bio: "Undergraduate student at the University of Pennsylvania. Incoming PhD student in Electrical Engineering with a focus on quantum technologies. Beyond engineering, I have experience in quantitative finance and data science."
  location: "Philadelphia, occasionally Hong Kong and London"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/valeriekyang"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-open-text"
      url: "valeang@seas.upenn.edu"
  - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/valerie-ky-ang/"

# Math Support (For your Quantum/Physics formulas)
markdown: kramdown
mathjax: true

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: true
